### ISSUE TITLE
创建git的软连接之后，每次执行命令行都会抛出异常：Exec /opt/homebrew/bin/git failed: exit status 1

### ISSUE THREAD

**Issue by ywooer** [fsgo/bin-auto-switcher#1]
主机版本：`macOS 13.2.1`
bin-auto-switcher版本：`v0.1.9`
git版本：`git version 2.38.1`（通过homebrew安装）
shell环境：`/bin/zsh` (安装了oh my zsh)

按照`readme.md`文档创建完`git`软连接，并配置`~/.config/bin-auto-switcher/git.toml`之后，
每次执行命令行命令都会抛出一行异常信息：`Exec /opt/homebrew/bin/git failed: exit status 1`
把shell环境切换到/bin/bash之后就恢复正常了。
查看了一下oh my zsh的脚本，里面有调用git的逻辑。请问这种情况需要怎么兼容一下呢？

**Comment by hidu** [comment]
删除 git 软连，在 ~/.zshrc 里添加 alias git="bas git"
