### ISSUE TITLE
配置多版本golang后使用dlv命令遇到问题

### ISSUE THREAD

**Issue by dongzeXD** [fsgo/bin-auto-switcher#2]
exec: "go": executable file not found in $PATH
请教下怎么解决

**Comment by hidu** [comment]
新的地址需要加入PATH环境变量。
一般是  
export PATH=$GOBIN:$PATH
这一行可以加入 .bashrc 或者.zshrc 文件




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月03日 11:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [fsgo/bin-auto-switcher] 配置多版本golang后使用dlv命令遇到问题 (Issue #2) |

exec: "go": executable file not found in $PATH
请教下怎么解决
